language: node_js
node_js:
- '0.12'
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database floodway_test;' -U postgres
before_install:
- openssl aes-256-cbc -K $encrypted_099a89b12a36_key -iv $encrypted_099a89b12a36_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar